AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: RCRA - Root Cause & Remediation Assistant (MVP)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Handler: index.handler
    Tracing: Active

Parameters:
  BedrockRegion:
    Type: String
    Default: us-east-1
  LogGroupName:
    Type: String
    Default: /aws/lambda/your-app-log-group

Resources:
  RCRATable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RCRARootCauseTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: IncidentId
          AttributeType: S
      KeySchema:
        - AttributeName: IncidentId
          KeyType: HASH

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: RCRANotifications

  RCRALogIngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rcra-log-ingest
      CodeUri: ../src/
      Handler: log_ingest_lambda.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - states:StartExecution
            Resource: "*"
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref RCRAStateMachine
      Events:
        CloudWatchLogs:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: !Ref LogGroupName
            FilterPattern: '"ERROR"'

  RCRAAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rcra-analyzer
      CodeUri: ../src/
      Handler: rca_analyzer_lambda.handler
      Environment:
        Variables:
          BEDROCK_REGION: !Ref BedrockRegion
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: "*"

  RCRARemediatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rcra-remediator
      CodeUri: ../src/
      Handler: enhanced_remediator_lambda.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref RCRATable
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - lambda:GetFunctionConfiguration
              - lambda:UpdateFunctionConfiguration
              - cloudwatch:PutMetricAlarm
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - dynamodb:GetItem
            Resource:
              - "*"
              - !GetAtt RCRATable.Arn

  RCRAPersistFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rcra-persist
      CodeUri: ../src/
      Handler: persist_lambda.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref RCRATable
          TOPIC_ARN: !Ref NotificationTopic
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName

  DummyAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rcra-dummy-app
      CodeUri: ../src/
      Handler: dummy_app_lambda.handler
      Timeout: 30
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /dummy-app
            Method: GET
            ApiId: !Ref RCRADashboardAPI

  RCRADashboardAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rcra-dashboard-api
      CodeUri: ../src/
      Handler: dashboard_api_lambda.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref RCRATable
          TOPIC_ARN: !Ref NotificationTopic
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref RCRATable
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource:
              - !GetAtt RCRATable.Arn
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !GetAtt DummyAppFunction.Arn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - Statement:
            Effect: Allow
            Action:
              - logs:FilterLogEvents
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - lambda:GetFunctionConfiguration
              - lambda:UpdateFunctionConfiguration
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: "*"
      Events:
        GetIncidents:
          Type: HttpApi
          Properties:
            Path: /incidents
            Method: GET
            ApiId: !Ref RCRADashboardAPI
        GetIncidentById:
          Type: HttpApi
          Properties:
            Path: /incidents/{id}
            Method: GET
            ApiId: !Ref RCRADashboardAPI
        GetIncidentLogs:
          Type: HttpApi
          Properties:
            Path: /incidents/{id}/logs
            Method: GET
            ApiId: !Ref RCRADashboardAPI
        GetStatistics:
          Type: HttpApi
          Properties:
            Path: /statistics
            Method: GET
            ApiId: !Ref RCRADashboardAPI
        OptionsIncidents:
          Type: HttpApi
          Properties:
            Path: /incidents
            Method: OPTIONS
            ApiId: !Ref RCRADashboardAPI
        OptionsStatistics:
          Type: HttpApi
          Properties:
            Path: /statistics
            Method: OPTIONS
            ApiId: !Ref RCRADashboardAPI
        TriggerError:
          Type: HttpApi
          Properties:
            Path: /trigger-error
            Method: GET
            ApiId: !Ref RCRADashboardAPI
        TriggerRemediation:
          Type: HttpApi
          Properties:
            Path: /remediate
            Method: POST
            ApiId: !Ref RCRADashboardAPI
        GetCriticalFunctions:
          Type: HttpApi
          Properties:
            Path: /config/critical-functions
            Method: GET
            ApiId: !Ref RCRADashboardAPI
        UpdateCriticalFunctions:
          Type: HttpApi
          Properties:
            Path: /config/critical-functions
            Method: POST
            ApiId: !Ref RCRADashboardAPI
        GetAutoRemediationConfig:
          Type: HttpApi
          Properties:
            Path: /config/auto-remediation
            Method: GET
            ApiId: !Ref RCRADashboardAPI
        UpdateAutoRemediationConfig:
          Type: HttpApi
          Properties:
            Path: /config/auto-remediation
            Method: POST
            ApiId: !Ref RCRADashboardAPI
        ResolveIncident:
          Type: HttpApi
          Properties:
            Path: /resolve
            Method: POST
            ApiId: !Ref RCRADashboardAPI
        GetPredictiveAnalysis:
          Type: HttpApi
          Properties:
            Path: /predictive-analysis
            Method: GET
            ApiId: !Ref RCRADashboardAPI

  RCRADashboardAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: RCRADashboardAPI
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS

  RCRAStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: RCRAStateMachine
      Definition:
        Comment: "RCRA MVP RCA and remediation flow"
        StartAt: Analyze
        States:
          Analyze:
            Type: Task
            Resource: !GetAtt RCRAAnalyzerFunction.Arn
            ResultPath: $.analysis
            Next: Remediate
          Remediate:
            Type: Task
            Resource: !GetAtt RCRARemediatorFunction.Arn
            ResultPath: $.remediation
            Next: Persist
          Persist:
            Type: Task
            Resource: !GetAtt RCRAPersistFunction.Arn
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref RCRAAnalyzerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RCRARemediatorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RCRAPersistFunction

Outputs:
  StateMachineArn:
    Description: ARN of the RCRA state machine
    Value: !Ref RCRAStateMachine
  NotificationTopicArn:
    Description: ARN of the SNS topic for notifications
    Value: !Ref NotificationTopic
  TableName:
    Description: DynamoDB table storing RCA records
    Value: !Ref RCRATable
  DashboardAPIEndpoint:
    Description: API Gateway endpoint URL for RCRA Dashboard
    Value: !Sub "https://${RCRADashboardAPI}.execute-api.${AWS::Region}.amazonaws.com"
